### ISSUE TITLE
missing from gnosis

### ISSUE THREAD

**Issue by martykebke** [GLCNI/ETH-Solo-Validator-Addresses#13]
Run ETH & Gnosis locally here but I'm only included on the ETH list and not Gnosis? Thanks 

0x1F27af0bAd8A2c7C38E68f548716E4ac003A2F17

![IMG_4486](https://github.com/GLCNI/ETH-Solo-Validator-Addresses/assets/113847185/571da73a-430f-4aca-ae83-ce2674ce0f6d)

**Comment by Stake-Cat** [comment]
The Gnosischain list will be updated soon and will include this address.
