### ISSUE TITLE
Solo staker missing 

### ISSUE THREAD

**Issue by FiloSofah** [GLCNI/ETH-Solo-Validator-Addresses#16]
Hi!
My validator is missing from the list(s)

0x86511810efa0411a6b1095c457ffed546282f1150e854831071e49b3bf035428b2e48f8f1d720eb230d01455acef1ab6

Staking since a month or two after genesis!
TIA

**Comment by Stake-Cat** [comment]
Associated Deposit address is present in `Solo-Stakers-A`
