### ISSUE TITLE
Validator Address is missing

### ISSUE THREAD

**Issue by bassoy** [GLCNI/ETH-Solo-Validator-Addresses#5]
Thanks for the efforts.

Yet I am not able to see my validator addresses of my validators nr [289465](https://beaconcha.in/validator/289465)  and nr [289464](https://beaconcha.in/validator/289464). 
Their addresses are 
`0x84ac84a97e29931a05b092deda247b9bb8be67a26d155a48b4ecb0abfb5f50fd6c96c12b43033be8e2eebb97e5cc8fae`
and 
`0xaa23c48e497b3469fa17ff39f5ebfc636567b50e76ee71749e3e29d327f4ac136ef9b462f7d031c2c43aa35e49bae439`

**Comment by GLCNI** [comment]
Hi, I found the ETH1 address associated with both validators is included in the list 

The issue might be its too large to be searchable unless downloaded
