### ISSUE TITLE
hmm, my ETH node is not in any of the lists

### ISSUE THREAD

**Issue by Ajes1337** [GLCNI/ETH-Solo-Validator-Addresses#9]
hmm, my ETH node is not in any of the lists, I staked back in july 2022. (and have been running ever since)

address: 0x8d3083f26DA78BACe17e16D643E549A721ac0088

32 eth deposit tx: https://etherscan.io/tx/0x3b40692450479c15832c8db6d30a0c2b15b316e157144f4aa568307e10e5ecdc

**Comment by GLCNI** [comment]
Seems this deposit was through the Abyss Finance smart contract, see Issue #10 for more details
